Repository prometheus-community/ansible, pull requests merged in 2023-03, with the labels that each got.

#33 fix: grab dependencies from github to avoid galaxy timeouts
  requirements.yml
  tests/integration/molecule.sh
Labels: bugfix

#34 fix: avoid installing changelog tools when testing
  test-requirements.txt
Labels: bugfix

#35 removed: remove lint from molecule to avoid repetition
  .config/molecule/config.yml
  test-requirements.txt
Labels: removed

#36 fix: Force push git changelogs
  .github/workflows/release.yml
Labels: bugfix

#37 fix: ansible 2.9 workaround for galaxy install from git
  tests/integration/molecule.sh
Labels: bugfix

#22 fix: Remove unnecessary dependency on jmespath
  roles/prometheus/README.md
  roles/prometheus/tasks/preflight.yml
  test-requirements.txt
Labels: bugfix

#28 feat: Allow grabbing binaries and checksums from a custom url/mirror
  roles/alertmanager/README.md
  roles/alertmanager/defaults/main.yml
  roles/alertmanager/tasks/install.yml
  roles/alertmanager/tasks/preflight.yml
  roles/blackbox_exporter/README.md
  roles/blackbox_exporter/defaults/main.yml
  roles/blackbox_exporter/tasks/install.yml
  roles/node_exporter/README.md
  roles/node_exporter/defaults/main.yml
  roles/node_exporter/tasks/install.yml
  roles/node_exporter/tasks/preflight.yml
  roles/prometheus/README.md
  roles/prometheus/defaults/main.yml
  roles/prometheus/tasks/install.yml
  roles/prometheus/tasks/preflight.yml
  roles/snmp_exporter/README.md
  roles/snmp_exporter/defaults/main.yml
  roles/snmp_exporter/tasks/install.yml
  roles/snmp_exporter/tasks/preflight.yml
Labels: enhancement

#40 skip_changelog: remove unneeded circleci script
  roles/prometheus/bump_version.sh
Labels: skip_changelog

#41 packaging: publish on ansible galaxy on release
  .github/workflows/publish.yml
Labels: trivial

#42 packaging: Fix publish action version
  .github/workflows/publish.yml
Labels: trivial

#27 docs: add argument specs to roles
  roles/alertmanager/meta/argument_specs.yml
  roles/blackbox_exporter/meta/argument_specs.yml
  roles/node_exporter/meta/argument_specs.yml
  roles/prometheus/meta/argument_specs.yml
  roles/snmp_exporter/meta/argument_specs.yml
Labels: trivial

#46 fix: follow PEP 440 standard for supported ansible versions
  .github/workflows/ansible-ci.yml
  meta/runtime.yml
Labels: bugfix

#47 refactor: move yamllint cfg to standard path
  .yamllint.yml
  tests/integration/molecule.sh
Labels: trivial

#51 skip_changelog: Trigger test CI workflow on PR commits
  .github/workflows/ansible-ci.yml
  .gitignore
Labels: skip_changelog

#50 fix: various role argument specs
  roles/alertmanager/meta/argument_specs.yml
  roles/blackbox_exporter/meta/argument_specs.yml
  roles/node_exporter/meta/argument_specs.yml
  roles/prometheus/defaults/main.yml
  roles/prometheus/meta/argument_specs.yml
  roles/prometheus/tasks/preflight.yml
  roles/snmp_exporter/meta/argument_specs.yml
Labels: bugfix

#56 removed: community.crypto is only needed when testing
  galaxy.yml
Labels: removed

#57 fix: Fix typo on Install selinux python packages for RedHat family
  roles/alertmanager/tasks/selinux.yml
  roles/node_exporter/tasks/selinux.yml
Labels: bugfix

#61 test: fix: 2.12+ test requirements install
  roles/blackbox_exporter/vars/redhat-7.yml
  roles/blackbox_exporter/vars/ubuntu.yml
  tests/integration/molecule.sh
Labels: trivial

#52 refactor: avoid using command module for systemd version fact
  roles/alertmanager/tasks/preflight.yml
  roles/alertmanager/templates/alertmanager.service.j2
  roles/blackbox_exporter/tasks/preflight.yml
  roles/blackbox_exporter/templates/blackbox_exporter.service.j2
  roles/node_exporter/tasks/preflight.yml
  roles/node_exporter/templates/node_exporter.service.j2
  roles/prometheus/tasks/preflight.yml
  roles/prometheus/templates/prometheus.service.j2
Labels: trivial

#66 skip_changelog: Don't run CI on push
  .github/workflows/ansible-ci.yml
Labels: skip_changelog

#48 skip-release: Add workflow to auto-update versions
  .github/workflows/version_bumper.yml
  roles/alertmanager/defaults/main.yml
  roles/blackbox_exporter/defaults/main.yml
  roles/node_exporter/defaults/main.yml
  roles/prometheus/defaults/main.yml
  roles/snmp_exporter/defaults/main.yml
  roles/systemd_exporter/defaults/main.yml
  version_updater.sh
Labels: skip_changelog

#63 fix: policycoreutils python package name
  roles/alertmanager/tasks/selinux.yml
  roles/node_exporter/tasks/selinux.yml
  roles/prometheus/vars/main.yml
Labels: bugfix

#45 feat: Add mysqld_exporter role
  roles/mysqld_exporter/README.md
  roles/mysqld_exporter/TROUBLESHOOTING.md
  roles/mysqld_exporter/defaults/main.yml
  roles/mysqld_exporter/handlers/main.yml
  roles/mysqld_exporter/meta/argument_specs.yml
  roles/mysqld_exporter/meta/main.yml
  roles/mysqld_exporter/molecule/alternative/converge.yml
  roles/mysqld_exporter/molecule/alternative/molecule.yml
  roles/mysqld_exporter/molecule/alternative/prepare.yml
  roles/mysqld_exporter/molecule/alternative/tests/test_alternative.py
  roles/mysqld_exporter/molecule/default/converge.yml
  roles/mysqld_exporter/molecule/default/molecule.yml
  roles/mysqld_exporter/molecule/default/tests/test_default.py
  roles/mysqld_exporter/molecule/latest/converge.yml
  roles/mysqld_exporter/molecule/latest/molecule.yml
  roles/mysqld_exporter/molecule/latest/tests/test_latest.py
  roles/mysqld_exporter/tasks/configure.yml
  roles/mysqld_exporter/tasks/install.yml
  roles/mysqld_exporter/tasks/main.yml
  roles/mysqld_exporter/tasks/preflight.yml
  roles/mysqld_exporter/tasks/selinux.yml
  roles/mysqld_exporter/templates/my_cnf.j2
  roles/mysqld_exporter/templates/mysqld_exporter.service.j2
  roles/mysqld_exporter/templates/web_config.yaml.j2
  roles/mysqld_exporter/test-requirements.txt
  roles/mysqld_exporter/vars/main.yml
  tests/integration/targets/molecule-mysqld_exporter-alternative/runme.sh
  tests/integration/targets/molecule-mysqld_exporter-default/runme.sh
  tests/integration/targets/molecule-mysqld_exporter-latest/runme.sh
Labels: enhancement

#70 skip_changelog: Use prom image for version script
  .github/workflows/version_bumper.yml
Labels: skip_changelog

#69 docs: add workflow for auto generating ansible docs
  .github/workflows/docs-pr.yml
  .github/workflows/docs-push.yml
  roles/alertmanager/meta/argument_specs.yml
Labels: trivial

#71 fix: correct quotation of flags in systemd config file
  roles/node_exporter/templates/node_exporter.service.j2
Labels: bugfix

#75 fix: version bumper action
  .github/workflows/version_bumper.yml
Labels: bugfix

#76 skip_changelog: fix docs pr workflow indent
  .github/workflows/docs-pr.yml
Labels: skip_changelog

#74 enhancement: add `skip_install` variables to various roles
  roles/alertmanager/README.md
  roles/alertmanager/defaults/main.yml
  roles/alertmanager/meta/argument_specs.yml
  roles/alertmanager/tasks/install.yml
  roles/alertmanager/tasks/preflight.yml
  roles/blackbox_exporter/README.md
  roles/blackbox_exporter/defaults/main.yml
  roles/blackbox_exporter/meta/argument_specs.yml
  roles/blackbox_exporter/tasks/install.yml
  roles/blackbox_exporter/tasks/preflight.yml
  roles/mysqld_exporter/README.md
  roles/mysqld_exporter/defaults/main.yml
  roles/mysqld_exporter/meta/argument_specs.yml
  roles/mysqld_exporter/tasks/install.yml
  roles/mysqld_exporter/tasks/preflight.yml
  roles/node_exporter/README.md
  roles/node_exporter/defaults/main.yml
  roles/node_exporter/meta/argument_specs.yml
  roles/node_exporter/tasks/install.yml
  roles/node_exporter/tasks/preflight.yml
  roles/snmp_exporter/README.md
  roles/snmp_exporter/defaults/main.yml
  roles/snmp_exporter/meta/argument_specs.yml
  roles/snmp_exporter/tasks/install.yml
  roles/snmp_exporter/tasks/preflight.yml
  roles/systemd_exporter/README.md
  roles/systemd_exporter/defaults/main.yml
  roles/systemd_exporter/meta/argument_specs.yml
  roles/systemd_exporter/tasks/install.yml
  roles/systemd_exporter/tasks/preflight.yml
Labels: enhancement
