Repository prometheus-community/ansible, pull requests merged in 2023-05, with the labels that each got.

#87 fix: tags support for included tasks
  roles/alertmanager/tasks/main.yml
  roles/blackbox_exporter/tasks/main.yml
  roles/mysqld_exporter/tasks/main.yml
  roles/node_exporter/tasks/main.yml
  roles/prometheus/tasks/main.yml
  roles/snmp_exporter/tasks/main.yml
  roles/systemd_exporter/tasks/main.yml
Labels: bugfix

#93 skip_changelog: Fix workflow outputs syntax
  .github/scripts/discover_role_repos.sh
  .github/workflows/version_bumper.yml
Labels: skip_changelog

#99 fix: add "become: true" to snmp_exporter handlers
  roles/snmp_exporter/handlers/main.yml
Labels: bugfix

#106 minor: Add ansible 2.15 support
  .github/workflows/ansible-ci.yml
  changelogs/changelog.yaml
  meta/runtime.yml
Labels: minor, alertmanager, node_exporter, prometheus, systemd_exporter, blackbox_exporter, snmp_exporter, mysqld_exporter

#108 fix: Checkout full branch for version updates
  .github/workflows/version_bumper.yml
Labels: bugfix

#109 fix: don't require role name on internal vars
  .config/ansible-lint.yml
Labels: bugfix

#104 docs: broken link to systemd exporter on docs
  roles/systemd_exporter/meta/argument_specs.yml
Labels: trivial

#110 skip_changelog: More fixes to version bumper
  .github/scripts/version_updater.sh
  .github/workflows/version_bumper.yml
Labels: skip_changelog

#111 skip_changelog: Fix typo in version bumper
  .github/workflows/version_bumper.yml
Labels: skip_changelog

#113 fix: always create config file
  roles/node_exporter/tasks/configure.yml
Labels: bugfix

#89 fix: Install package fact dependencies needs to be run as root
  roles/alertmanager/tasks/preflight.yml
  roles/blackbox_exporter/tasks/preflight.yml
  roles/mysqld_exporter/tasks/preflight.yml
  roles/node_exporter/tasks/preflight.yml
  roles/prometheus/tasks/preflight.yml
  roles/systemd_exporter/tasks/preflight.yml
Labels: bugfix, alertmanager, node_exporter, prometheus, systemd_exporter, blackbox_exporter, mysqld_exporter

#112 skip_changelog: unify automatic and manual ansible role tests with labels
  .github/workflows/ansible-ci.yml
  .github/workflows/conventional-label.yml
Labels: skip_changelog

#119 skip_changelog: Add prombot DCO
  .github/scripts/version_updater.sh
Labels: skip_changelog

#126 skip_changelog: Fix version updater DCO
  .github/scripts/version_updater.sh
Labels: skip_changelog
