Repository prometheus-community/ansible, pull requests merged in 2024-09, with the labels that each got.

#416 fix: ansible-community/eol-ansible for 2.9/2.10/2.11 tests
  .github/workflows/ansible-test-integration.yml
  .github/workflows/ansible-test-sanity.yml
Labels: bugfix

#407 enhancement: adding env/container labels options
  roles/cadvisor/defaults/main.yml
  roles/cadvisor/meta/argument_specs.yml
  roles/cadvisor/molecule/alternative/molecule.yml
  roles/cadvisor/templates/cadvisor.service.j2
Labels: enhancement, roles/cadvisor

#414 minor: bump support for ansible from v2.16.* to v2.17.*
  .config/molecule/config.yml
  meta/runtime.yml
  tests/integration/molecule.sh
  tests/sanity/ignore-2.17.txt
Labels: minor, roles/alertmanager, roles/node_exporter, roles/prometheus, roles/systemd_exporter, roles/blackbox_exporter, roles/snmp_exporter, roles/mysqld_exporter, roles/smokeping_prober, roles/pushgateway, roles/chrony_exporter, roles/smartctl_exporter, roles/memcached_exporter, roles/ipmi_exporter, roles/cadvisor, roles/nginx_exporter, roles/postgres_exporter, roles/fail2ban_exporter, roles/mongodb_exporter, roles/redis_exporter, roles/process_exporter, roles/bind_exporter
