Repository prometheus-community/ansible, pull requests merged in 2024-06, with the labels that each got.

#372 docs: redirect docs page to latest release instead of docs for upcoming release
  .github/workflows/docs-pr.yml
  .github/workflows/docs-push.yml
Labels: trivial

#378 removed: Drop centos 8 stream support as it is EOL
  .config/molecule/config.yml
Labels: removed

#373 docs: fix config_flags_extra wrong example
  roles/prometheus/meta/argument_specs.yml
Labels: trivial, roles/prometheus

#383 skip_changelog: Fix version updater script
  .github/scripts/version_updater.sh
Labels: skip_changelog

#367 fix: make sure antsibull-changelog doesn't offend ansible-lint
  .github/workflows/release.yml
  changelogs/config.yaml
Labels: bugfix
